#!/usr/bin/env python

# Copyright 2024 Columbia Artificial Intelligence, Robotics Lab,
# and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from collections import deque
from functools import partial
from typing import Callable
from typing_extensions import override

import einops
import torchvision

from lerobot.constants import ACTION, OBS_ENV_STATE, OBS_IMAGES, OBS_STATE
from lerobot_policy_unetmeanflow.configuration_unetmeanflow import UnetMeanFlowConfig
from lerobot.policies.normalize import Normalize, Unnormalize
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import (
    get_device_from_parameters,
    get_dtype_from_parameters,
    get_output_shape,
    populate_queues,
)


class UnetMeanFlowPolicy(PreTrainedPolicy):
    """
    U-Net MeanFlow Policy combining U-Net architecture with meanflow algorithm.

    This policy merges the convolutional U-Net backbone from DiffusionPolicy with
    the meanflow algorithm from DiTMeanFlow for efficient one-step action generation.
    """

    config_class = UnetMeanFlowConfig
    name = "unetmeanflow"

    def __init__(
        self,
        config: UnetMeanFlowConfig,
        dataset_stats: dict[str, dict[str, torch.Tensor]] | None = None,
    ):
        """
        Args:
            config: Policy configuration class instance or None, in which case the default instantiation of
                the configuration class is used.
            dataset_stats: Dataset statistics to be used for normalization. If not passed here, it is expected
                that they will be passed with a call to `load_state_dict` before the policy is used.
        """
        super().__init__(config)
        config.validate_features()
        self.config = config

        self.normalize_inputs = Normalize(config.input_features, config.normalization_mapping, dataset_stats)
        self.normalize_targets = Normalize(
            config.output_features, config.normalization_mapping, dataset_stats
        )
        self.unnormalize_outputs = Unnormalize(
            config.output_features, config.normalization_mapping, dataset_stats
        )

        # queues are populated during rollout of the policy, they contain the n latest observations and actions
        self._queues = None

        self.unet_meanflow = UnetMeanFlowModel(config)

        self.reset()

    def get_optim_params(self) -> dict:
        return self.unet_meanflow.parameters()

    def reset(self):
        """Clear observation and action queues. Should be called on `env.reset()`"""
        self._queues = {
            "observation.state": deque(maxlen=self.config.n_obs_steps),
            "action": deque(maxlen=self.config.n_action_steps),
        }
        if self.config.image_features:
            self._queues["observation.images"] = deque(maxlen=self.config.n_obs_steps)
        if self.config.env_state_feature:
            self._queues["observation.environment_state"] = deque(maxlen=self.config.n_obs_steps)

    @torch.no_grad()
    def predict_action_chunk(self, batch: dict[str, torch.Tensor]) -> torch.Tensor:
        """Predict a chunk of actions given environment observations."""
        # stack n latest observations from the queue
        batch = {k: torch.stack(list(self._queues[k]), dim=1) for k in batch if k in self._queues}
        actions = self.unet_meanflow.generate_actions(batch)

        actions = self.unnormalize_outputs({ACTION: actions})[ACTION]

        return actions

    @torch.no_grad()
    def select_action(self, batch: dict[str, torch.Tensor]) -> torch.Tensor:
        """Select a single action given environment observations.

        This method handles caching a history of observations and an action trajectory generated by the
        underlying meanflow model. Here's how it works:
          - `n_obs_steps` steps worth of observations are cached (for the first steps, the observation is
            copied `n_obs_steps` times to fill the cache).
          - The meanflow model generates `horizon` steps worth of actions.
          - `n_action_steps` worth of actions are actually kept for execution, starting from the current step.
        Schematically this looks like:
            ----------------------------------------------------------------------------------------------
            (legend: o = n_obs_steps, h = horizon, a = n_action_steps)
            |timestep            | n-o+1 | n-o+2 | ..... | n     | ..... | n+a-1 | n+a   | ..... | n-o+h |
            |observation is used | YES   | YES   | YES   | YES   | NO    | NO    | NO    | NO    | NO    |
            |action is generated | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   |
            |action is used      | NO    | NO    | NO    | YES   | YES   | YES   | NO    | NO    | NO    |
            ----------------------------------------------------------------------------------------------
        Note that this means we require: `n_action_steps <= horizon - n_obs_steps + 1`. Also, note that
        "horizon" may not the best name to describe what the variable actually means, because this period is
        actually measured from the first observation which (if `n_obs_steps` > 1) happened in the past.
        """
        batch = self.normalize_inputs(batch)
        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        # Note: It's important that this happens after stacking the images into a single key.
        self._queues = populate_queues(self._queues, batch)

        if len(self._queues[ACTION]) == 0:
            actions = self.predict_action_chunk(batch)
            self._queues[ACTION].extend(actions.transpose(0, 1))

        action = self._queues[ACTION].popleft()
        return action

    def forward(self, batch: dict[str, torch.Tensor]) -> tuple[torch.Tensor, None]:
        """Run the batch through the model and compute the loss for training or validation."""
        batch = self.normalize_inputs(batch)
        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        batch = self.normalize_targets(batch)
        loss = self.unet_meanflow.compute_loss(batch)
        # no output_dict so returning None
        return loss, None


class UnetMeanFlowModel(nn.Module):
    def __init__(self, config: UnetMeanFlowConfig):
        super().__init__()
        self.config = config

        # Build observation encoders (depending on which observations are provided).
        global_cond_dim = self.config.robot_state_feature.shape[0]
        if self.config.image_features:
            num_images = len(self.config.image_features)
            if self.config.use_separate_rgb_encoder_per_camera:
                encoders = [UnetMeanFlowRgbEncoder(config) for _ in range(num_images)]
                self.rgb_encoder = nn.ModuleList(encoders)
                global_cond_dim += encoders[0].feature_dim * num_images
            else:
                self.rgb_encoder = UnetMeanFlowRgbEncoder(config)
                global_cond_dim += self.rgb_encoder.feature_dim * num_images
        if self.config.env_state_feature:
            global_cond_dim += self.config.env_state_feature.shape[0]

        self.unet = UnetMeanFlowConditionalUnet1d(
            config, global_cond_dim=global_cond_dim * config.n_obs_steps
        )

        # FIXED: Add JVP configuration (based on DiTMeanFlow)
        self.jvp_func = None
        if self.config.use_autograd_functional_jvp:
            import torch.autograd.functional

            self.jvp_func = partial(torch.autograd.functional.jvp, create_graph=True)
        else:
            import torch.func

            self.jvp_func = torch.func.jvp

        print(
            f"UnetMeanFlowModel with {sum(p.numel() for p in self.parameters() if p.requires_grad)} parameters."
        )

    def jvp(self, func, primals, tangents):
        """Compute the Jacobian-vector product using the selected method."""
        if self.jvp_func is None:
            raise ValueError("JVP function not initialized.")
        return self.jvp_func(func, primals, tangents)

    # ========= inference  ============
    def conditional_sample(
        self,
        batch_size: int,
        global_cond: torch.Tensor | None = None,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        device = get_device_from_parameters(self)
        dtype = get_dtype_from_parameters(self)

        # Sample prior.
        sample = torch.randn(
            size=(batch_size, self.config.horizon, self.config.action_feature.shape[0]),
            dtype=dtype,
            device=device,
            generator=generator,
        )

        # MeanFlow sampling - use one-step by default for efficiency
        if self.config.do_multi_step_sampling:
            sample = self._sample_multi_step(sample, global_cond, generator)
        else:
            sample = self._sample_one_step(sample, global_cond, generator)

        return sample

    @torch.no_grad()
    def _sample_one_step(
        self,
        sample: torch.Tensor,
        global_cond: torch.Tensor | None = None,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        """Sample using one-step meanflow inference."""
        batch_size, device = sample.shape[0], sample.device
        t = torch.ones(batch_size, device=device)
        r = torch.zeros(batch_size, device=device)

        # One-step meanflow: x_0 = x_T - u(x_T, t=1, r=0)
        velocity = self.unet(sample, t, r, global_cond=global_cond)
        sample = sample - velocity

        if self.config.clip_sample:
            sample = torch.clamp(sample, -self.config.clip_sample_range, self.config.clip_sample_range)

        return sample

    @torch.no_grad()
    def _sample_multi_step(
        self,
        sample: torch.Tensor,
        global_cond: torch.Tensor | None = None,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        """Sample using multi-step meanflow inference."""
        batch_size, device = sample.shape[0], sample.device
        timesteps = self.config.inference_timesteps
        dt = 1.0 / timesteps

        # FIXED: Use linspace with timesteps + 1 (matching DiTMeanFlow)
        t_vals = torch.linspace(0.0, 1.0, timesteps + 1, device=device)

        for k in range(timesteps):
            # FIXED: Use torch.full for consistent batch dimensions and proper indexing
            t = torch.full((batch_size,), t_vals[k], device=device)
            r = torch.full((batch_size,), t_vals[k + 1], device=device)

            # FIXED: Get velocity and integrate properly
            u = self.unet(sample, t=t, r=r, global_cond=global_cond)
            sample = sample - dt * u

            if self.config.clip_sample:
                sample = torch.clamp(sample, -self.config.clip_sample_range, self.config.clip_sample_range)

        return sample

    def _prepare_global_conditioning(self, batch: dict[str, torch.Tensor]) -> torch.Tensor:
        """Encode image features and concatenate them all together along with the state vector."""
        batch_size, n_obs_steps = batch[OBS_STATE].shape[:2]
        global_cond_feats = []
        robot_state = batch[OBS_STATE]
        if len(robot_state.shape) == 4:
            robot_state = robot_state[:, :, 0, ...]
        global_cond_feats.append(robot_state)

        # Extract image features.
        if self.config.image_features:
            images = batch["observation.images"]
            if len(images.shape) == 7:
                images = images[:, :, 0, ...]

            if self.config.use_separate_rgb_encoder_per_camera:
                # Combine batch and sequence dims while rearranging to make the camera index dimension first.
                images_per_camera = einops.rearrange(images, "b s n ... -> n (b s) ...")
                img_features_list = torch.cat(
                    [
                        encoder(images)
                        for encoder, images in zip(self.rgb_encoder, images_per_camera, strict=True)
                    ]
                )
                # Separate batch and sequence dims back out. The camera index dim gets absorbed into the
                # feature dim (effectively concatenating the camera features).
                img_features = einops.rearrange(
                    img_features_list, "(n b s) ... -> b s (n ...)", b=batch_size, s=n_obs_steps
                )
            else:
                # Combine batch, sequence, and "which camera" dims before passing to shared encoder.
                img_features = self.rgb_encoder(einops.rearrange(images, "b s n ... -> (b s n) ..."))
                # Separate batch dim and sequence dim back out. The camera index dim gets absorbed into the
                # feature dim (effectively concatenating the camera features).
                img_features = einops.rearrange(
                    img_features, "(b s n) ... -> b s (n ...)", b=batch_size, s=n_obs_steps
                )
            global_cond_feats.append(img_features)

        if self.config.env_state_feature:
            global_cond_feats.append(batch[OBS_ENV_STATE])

        # Concatenate features then flatten to (B, global_cond_dim).
        return torch.cat(global_cond_feats, dim=-1).flatten(start_dim=1)

    def generate_actions(self, batch: dict[str, torch.Tensor]) -> torch.Tensor:
        """
        This function expects `batch` to have:
        {
            "observation.state": (B, n_obs_steps, state_dim)

            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, environment_dim)
        }
        """
        batch_size, n_obs_steps = batch["observation.state"].shape[:2]
        assert n_obs_steps == self.config.n_obs_steps

        # Encode image features and concatenate them all together along with the state vector.
        global_cond = self._prepare_global_conditioning(batch)  # (B, global_cond_dim)

        # run sampling
        actions = self.conditional_sample(batch_size, global_cond=global_cond)

        # Extract `n_action_steps` steps worth of actions (from the current observation).
        start = n_obs_steps - 1
        end = start + self.config.n_action_steps
        actions = actions[:, start:end]

        return actions

    def compute_loss(self, batch: dict[str, torch.Tensor]) -> torch.Tensor:
        """
        This function expects `batch` to have (at least):
        {
            "observation.state": (B, n_obs_steps, state_dim)

            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, environment_dim)

            "action": (B, horizon, action_dim)
            "action_is_pad": (B, horizon)
        }
        """
        # Input validation.
        assert set(batch).issuperset({"observation.state", "action", "action_is_pad"})
        # assert "observation.images" in batch or "observation.environment_state" in batch
        n_obs_steps = batch["observation.state"].shape[1]
        horizon = batch["action"].shape[1]
        assert horizon == self.config.horizon
        assert n_obs_steps == self.config.n_obs_steps

        # Encode image features and concatenate them all together along with the state vector.
        global_cond = self._prepare_global_conditioning(batch)  # (B, global_cond_dim)

        # Forward diffusion.
        trajectory = batch[ACTION]
        batch_size = trajectory.shape[0]
        device = trajectory.device

        if self.config.use_meanflow:
            loss = self._mean_flow_loss(
                batch_size=batch_size,
                device=device,
                trajectory=trajectory,
                global_cond=global_cond,
            )
        else:
            loss = self._flow_loss(
                batch_size=batch_size,
                device=device,
                trajectory=trajectory,
                global_cond=global_cond,
            )

        # Mask loss wherever the action is padded with copies (edges of the dataset trajectory).
        if self.config.do_mask_loss_for_padding:
            if "action_is_pad" not in batch:
                raise ValueError(
                    "You need to provide 'action_is_pad' in the batch when "
                    f"{self.config.do_mask_loss_for_padding=}."
                )
            in_episode_bound = ~batch["action_is_pad"]
            loss = loss * in_episode_bound.unsqueeze(-1)

        return loss.mean()

    def _sample_t_and_r(
        self,
        batch_size: int,
        device,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Sample a random noising timestep t and r for each item in the batch.

        Args:
            batch_size: Number of samples to draw.
            device: Device to place the tensors on.
        Returns:
            t: Noising timesteps. Shape: (batch_size,)
            r: Second noising timesteps for meanflow. Shape: (batch_size,)
        """
        samples = self._sample_time_distribution(batch_size=batch_size, num_time_parameters=2)

        t_np = np.maximum(samples[:, 0], samples[:, 1])
        r_np = np.minimum(samples[:, 0], samples[:, 1])

        num_selected = int(self.config.flow_ratio * batch_size)
        indices = np.random.permutation(batch_size)[:num_selected]
        r_np[indices] = t_np[indices]

        t = torch.tensor(t_np, device=device)
        r = torch.tensor(r_np, device=device)
        return t, r

    def _sample_t(self, batch_size: int, device) -> torch.Tensor:
        """Sample a random noising timestep t for each item in the batch."""
        samples = self._sample_time_distribution(batch_size=batch_size, num_time_parameters=1)
        t = torch.tensor(samples[:, 0], device=device)
        return t

    def _sample_time_distribution(self, batch_size: int, num_time_parameters: int) -> np.ndarray:
        """Sample from the configured time distribution.

        Args:
            batch_size: Number of samples to draw.
            num_time_parameters: Number of time parameters to sample per batch item (e.g., 2 for t and r and 1 for only t).
        Returns:
            samples: Sampled time parameters. Shape: (batch_size, num_time_parameters)
        """
        if self.config.time_distribution == "uniform":
            samples = np.random.rand(batch_size, num_time_parameters).astype(np.float32)
        elif self.config.time_distribution == "lognorm":
            normal_samples = (
                np.random.randn(batch_size, num_time_parameters).astype(np.float32)
                * self.config.log_norm_sigma
                + self.config.log_norm_mu
            )
            samples = 1 / (1 + np.exp(-normal_samples))  # Apply sigmoid
        else:
            raise ValueError(f"Unknown time distribution: {self.config.time_distribution}")
        return samples

    @staticmethod
    def adaptive_l2_loss(u, u_target, gamma=0.5, c=1e-3):
        """Adaptive L2 loss as in AdaLFD paper.

        Args:
            u: Predicted velocity
            u_target: Target velocity (should be detached)
            gamma: Power used in original ||Δ||^{2γ} loss
            c: Small constant for stability
        Returns:
            Scalar loss
        """
        error = u - u_target
        delta_sq = torch.mean(error**2, dim=tuple(range(1, error.ndim)))
        p = 1.0 - gamma
        w = 1.0 / (delta_sq + c).pow(p)
        loss = delta_sq
        return (w.detach() * loss).mean()

    def _mean_flow_loss(
        self,
        batch_size: int,
        device: torch.device,
        trajectory: torch.Tensor,
        global_cond: torch.Tensor,
    ) -> torch.Tensor:
        # Sample noise to add to the trajectory.
        noise = torch.randn(trajectory.shape, device=device)

        # Sample a random noising timestep for each item in the batch.
        t, r = self._sample_t_and_r(batch_size=batch_size, device=device)
        t_ = t[:, None, None]
        r_ = r[:, None, None]

        # Add noise to the clean trajectories according to the noise magnitude at each timestep.
        noisy_trajectory: torch.Tensor = (1 - t_) * trajectory + t_ * noise

        v = noise - trajectory
        if self.config.use_classifier_free_guidance:
            conditional_mask = torch.rand_like(t) < self.config.cfg_prob
            unconditional_cond = torch.zeros_like(global_cond)
            global_cond = torch.where(
                condition=conditional_mask.unsqueeze(-1), input=unconditional_cond, other=global_cond
            )
            with torch.no_grad():
                u_uncond = self.unet(
                    noisy_trajectory,
                    t=t,
                    r=t,
                    global_cond=unconditional_cond,
                )
            v_hat = self.config.cfg_omega * v + (1 - self.config.cfg_omega) * u_uncond
            v_hat = torch.where(condition=conditional_mask.unsqueeze(-1).unsqueeze(-1), input=v, other=v_hat)
        else:
            v_hat = v

        # We use the jvp to compute dudt between t and r.
        # This used to compute the mean target velocity used in the loss.
        def model_partial(z_k, t_k, r_k, **kwargs):
            return self.unet(
                z_k,
                t_k,
                r_k,
                global_cond=global_cond,
            )

        # FIXED: Use configurable jvp method
        u, dudt = self.jvp(
            func=model_partial,
            primals=(noisy_trajectory, t, r),
            tangents=(v_hat, torch.ones_like(t), torch.zeros_like(r)),
        )

        # Compute the target velocity for meanflow.
        u_target = v_hat - (t_ - r_) * dudt

        # Compute the loss.
        if self.config.use_adaptative_loss:
            loss = self.adaptive_l2_loss(u, u_target.detach())
        else:
            loss = F.mse_loss(u, u_target.detach(), reduction="none")

        return loss

    def _flow_loss(
        self,
        batch_size: int,
        device: torch.device,
        trajectory: torch.Tensor,
        global_cond: torch.Tensor,
    ) -> torch.Tensor:
        # Sample noise to add to the trajectory.
        noise = torch.randn(trajectory.shape, device=device)

        # Sample a random noising timestep for each item in the batch.
        t = self._sample_t(batch_size=batch_size, device=device)
        t_ = t[:, None, None]

        noisy_trajectory: torch.Tensor = (1 - t_) * trajectory + t_ * noise

        v = noise - trajectory  # target velocity

        u = self.unet(  # predicted velocity
            noisy_trajectory,
            t,
            t,  # r is not used in standard flow
            global_cond=global_cond,
        )
        loss = F.mse_loss(u, v.detach(), reduction="none")
        return loss


class UnetMeanFlowSinusoidalPosEmb(nn.Module):
    """1D sinusoidal positional embeddings as in Attention is All You Need."""

    def __init__(self, dim: int):
        super().__init__()
        self.dim = dim

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        device = x.device
        half_dim = self.dim // 2
        emb = math.log(10000) / (half_dim - 1)
        emb = torch.exp(torch.arange(half_dim, device=device) * -emb)
        emb = x.unsqueeze(-1) * emb.unsqueeze(0)
        emb = torch.cat((emb.sin(), emb.cos()), dim=-1)
        return emb


class UnetMeanFlowConv1dBlock(nn.Module):
    """Conv1d --> GroupNorm --> Mish"""

    def __init__(self, inp_channels, out_channels, kernel_size, n_groups=8):
        super().__init__()

        self.block = nn.Sequential(
            nn.Conv1d(inp_channels, out_channels, kernel_size, padding=kernel_size // 2),
            nn.GroupNorm(n_groups, out_channels),
            nn.Mish(),
        )

    def forward(self, x):
        return self.block(x)


class UnetMeanFlowConditionalUnet1d(nn.Module):
    """A 1D convolutional UNet with FiLM modulation for conditioning, adapted for meanflow.

    This U-Net accepts dual time parameters (t and r) for meanflow algorithm.
    """

    def __init__(self, config: UnetMeanFlowConfig, global_cond_dim: int):
        super().__init__()

        self.config = config

        # Encoder for the diffusion timestep - we need two encoders for t and r
        self.diffusion_step_encoder_t = nn.Sequential(
            UnetMeanFlowSinusoidalPosEmb(config.diffusion_step_embed_dim),
            nn.Linear(config.diffusion_step_embed_dim, config.diffusion_step_embed_dim * 4),
            nn.Mish(),
            nn.Linear(config.diffusion_step_embed_dim * 4, config.diffusion_step_embed_dim),
        )

        self.diffusion_step_encoder_r = nn.Sequential(
            UnetMeanFlowSinusoidalPosEmb(config.diffusion_step_embed_dim),
            nn.Linear(config.diffusion_step_embed_dim, config.diffusion_step_embed_dim * 4),
            nn.Mish(),
            nn.Linear(config.diffusion_step_embed_dim * 4, config.diffusion_step_embed_dim),
        )

        # The FiLM conditioning dimension - includes both time embeddings
        cond_dim = 2 * config.diffusion_step_embed_dim + global_cond_dim

        # In channels / out channels for each downsampling block in the Unet's encoder. For the decoder, we
        # just reverse these.
        in_out = [(config.action_feature.shape[0], config.down_dims[0])] + list(
            zip(config.down_dims[:-1], config.down_dims[1:], strict=True)
        )

        # Unet encoder.
        common_res_block_kwargs = {
            "cond_dim": cond_dim,
            "kernel_size": config.kernel_size,
            "n_groups": config.n_groups,
            "use_film_scale_modulation": config.use_film_scale_modulation,
        }
        self.down_modules = nn.ModuleList([])
        for ind, (dim_in, dim_out) in enumerate(in_out):
            is_last = ind >= (len(in_out) - 1)
            self.down_modules.append(
                nn.ModuleList(
                    [
                        UnetMeanFlowConditionalResidualBlock1d(dim_in, dim_out, **common_res_block_kwargs),
                        UnetMeanFlowConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Downsample as long as it is not the last block.
                        nn.Conv1d(dim_out, dim_out, 3, 2, 1) if not is_last else nn.Identity(),
                    ]
                )
            )

        # Processing in the middle of the auto-encoder.
        self.mid_modules = nn.ModuleList(
            [
                UnetMeanFlowConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **common_res_block_kwargs
                ),
                UnetMeanFlowConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **common_res_block_kwargs
                ),
            ]
        )

        # Unet decoder.
        self.up_modules = nn.ModuleList([])
        for ind, (dim_out, dim_in) in enumerate(reversed(in_out[1:])):
            is_last = ind >= (len(in_out) - 1)
            self.up_modules.append(
                nn.ModuleList(
                    [
                        # dim_in * 2, because it takes the encoder's skip connection as well
                        UnetMeanFlowConditionalResidualBlock1d(
                            dim_in * 2, dim_out, **common_res_block_kwargs
                        ),
                        UnetMeanFlowConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Upsample as long as it is not the last block.
                        nn.ConvTranspose1d(dim_out, dim_out, 4, 2, 1) if not is_last else nn.Identity(),
                    ]
                )
            )

        self.final_conv = nn.Sequential(
            UnetMeanFlowConv1dBlock(config.down_dims[0], config.down_dims[0], kernel_size=config.kernel_size),
            nn.Conv1d(config.down_dims[0], config.action_feature.shape[0], 1),
        )

    def forward(self, x: torch.Tensor, t: torch.Tensor, r: torch.Tensor, global_cond=None) -> torch.Tensor:
        """
        Args:
            x: (B, T, input_dim) tensor for input to the Unet.
            t: (B,) tensor of first timestep.
            r: (B,) tensor of second timestep for meanflow.
            global_cond: (B, global_cond_dim)
        Returns:
            (B, T, input_dim) velocity prediction.
        """
        # For 1D convolutions we'll need feature dimension first.
        x = einops.rearrange(x, "b t d -> b d t")

        # Encode both time parameters
        timesteps_embed_t = self.diffusion_step_encoder_t(t)
        # FIXED: Encode (t - r) instead of r directly (matching DiTMeanFlow)
        timesteps_embed_r = self.diffusion_step_encoder_r(t - r)

        # Combine time embeddings
        timesteps_embed = torch.cat([timesteps_embed_t, timesteps_embed_r], dim=-1)

        # If there is a global conditioning feature, concatenate it to the timestep embedding.
        if global_cond is not None:
            global_feature = torch.cat([timesteps_embed, global_cond], axis=-1)
        else:
            global_feature = timesteps_embed

        # Run encoder, keeping track of skip features to pass to the decoder.
        encoder_skip_features: list[torch.Tensor] = []
        for resnet, resnet2, downsample in self.down_modules:
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            encoder_skip_features.append(x)
            x = downsample(x)

        for mid_module in self.mid_modules:
            x = mid_module(x, global_feature)

        # Run decoder, using the skip features from the encoder.
        for resnet, resnet2, upsample in self.up_modules:
            x = torch.cat((x, encoder_skip_features.pop()), dim=1)
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            x = upsample(x)

        x = self.final_conv(x)

        x = einops.rearrange(x, "b d t -> b t d")
        return x


class UnetMeanFlowConditionalResidualBlock1d(nn.Module):
    """ResNet style 1D convolutional block with FiLM modulation for conditioning."""

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        cond_dim: int,
        kernel_size: int = 3,
        n_groups: int = 8,
        # Set to True to do scale modulation with FiLM as well as bias modulation (defaults to False meaning
        # FiLM just modulates bias).
        use_film_scale_modulation: bool = False,
    ):
        super().__init__()

        self.use_film_scale_modulation = use_film_scale_modulation
        self.out_channels = out_channels

        self.conv1 = UnetMeanFlowConv1dBlock(in_channels, out_channels, kernel_size, n_groups=n_groups)

        # FiLM modulation (https://huggingface.co/papers/1709.07871) outputs per-channel bias and (maybe) scale.
        cond_channels = out_channels * 2 if use_film_scale_modulation else out_channels
        self.cond_encoder = nn.Sequential(nn.Mish(), nn.Linear(cond_dim, cond_channels))

        self.conv2 = UnetMeanFlowConv1dBlock(out_channels, out_channels, kernel_size, n_groups=n_groups)

        # A final convolution for dimension matching the residual (if needed).
        self.residual_conv = (
            nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels else nn.Identity()
        )

    def forward(self, x: torch.Tensor, cond: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: (B, in_channels, T)
            cond: (B, cond_dim)
        Returns:
            (B, out_channels, T)
        """
        out = self.conv1(x)

        # Get condition embedding. Unsqueeze for broadcasting to `out`, resulting in (B, out_channels, 1).
        cond_embed = self.cond_encoder(cond).unsqueeze(-1)
        if self.use_film_scale_modulation:
            # Treat the embedding as a list of scales and biases.
            scale = cond_embed[:, : self.out_channels]
            bias = cond_embed[:, self.out_channels :]
            out = scale * out + bias
        else:
            # Treat the embedding as biases.
            out = out + cond_embed

        out = self.conv2(out)
        out = out + self.residual_conv(x)
        return out


class SpatialSoftmax(nn.Module):
    """
    Spatial Soft Argmax operation described in "Deep Spatial Autoencoders for Visuomotor Learning" by Finn et al.
    (https://huggingface.co/papers/1509.06113). A minimal port of the robomimic implementation.

    At a high level, this takes 2D feature maps (from a convnet/ViT) and returns the "center of mass"
    of activations of each channel, i.e., keypoints in the image space for the policy to focus on.

    Example: take feature maps of size (512x10x12). We generate a grid of normalized coordinates (10x12x2):
    -----------------------------------------------------
    | (-1., -1.)   | (-0.82, -1.)   | ... | (1., -1.)   |
    | (-1., -0.78) | (-0.82, -0.78) | ... | (1., -0.78) |
    | ...          | ...            | ... | ...         |
    | (-1., 1.)    | (-0.82, 1.)    | ... | (1., 1.)    |
    -----------------------------------------------------
    This is achieved by applying channel-wise softmax over the activations (512x120) and computing the dot
    product with the coordinates (120x2) to get expected points of maximal activation (512x2).

    The example above results in 512 keypoints (corresponding to the 512 input channels). We can optionally
    provide num_kp != None to control the number of keypoints. This is achieved by a first applying a learnable
    linear mapping (in_channels, H, W) -> (num_kp, H, W).
    """

    def __init__(self, input_shape, num_kp=None):
        """
        Args:
            input_shape (list): (C, H, W) input feature map shape.
            num_kp (int): number of keypoints in output. If None, output will have the same number of channels as input.
        """
        super().__init__()

        assert len(input_shape) == 3
        self._in_c, self._in_h, self._in_w = input_shape

        if num_kp is not None:
            self.nets = torch.nn.Conv2d(self._in_c, num_kp, kernel_size=1)
            self._out_c = num_kp
        else:
            self.nets = None
            self._out_c = self._in_c

        # we could use torch.linspace directly but that seems to behave slightly differently than numpy
        # and causes a small degradation in pc_success of pre-trained models.
        pos_x, pos_y = np.meshgrid(np.linspace(-1.0, 1.0, self._in_w), np.linspace(-1.0, 1.0, self._in_h))
        pos_x = torch.from_numpy(pos_x.reshape(self._in_h * self._in_w, 1)).float()
        pos_y = torch.from_numpy(pos_y.reshape(self._in_h * self._in_w, 1)).float()
        # register as buffer so it's moved to the correct device.
        self.register_buffer("pos_grid", torch.cat([pos_x, pos_y], dim=1))

    def forward(self, features: torch.Tensor) -> torch.Tensor:
        """
        Args:
            features: (B, C, H, W) input feature maps.
        Returns:
            (B, K, 2) image-space coordinates of keypoints.
        """
        if self.nets is not None:
            features = self.nets(features)

        # [B, K, H, W] -> [B * K, H * W] where K is number of keypoints
        features = features.reshape(-1, self._in_h * self._in_w)
        # 2d softmax normalization
        attention = F.softmax(features, dim=-1)
        # [B * K, H * W] x [H * W, 2] -> [B * K, 2] for spatial coordinate mean in x and y dimensions
        expected_xy = attention @ self.pos_grid
        # reshape to [B, K, 2]
        feature_keypoints = expected_xy.view(-1, self._out_c, 2)

        return feature_keypoints


class UnetMeanFlowRgbEncoder(nn.Module):
    """Encodes an RGB image into a 1D feature vector.

    Includes the ability to normalize and crop the image first.
    """

    def __init__(self, config: UnetMeanFlowConfig):
        super().__init__()
        # Set up optional preprocessing.
        if config.crop_shape is not None:
            self.do_crop = True
            # Always use center crop for eval
            self.center_crop = torchvision.transforms.CenterCrop(config.crop_shape)
            if config.crop_is_random:
                self.maybe_random_crop = torchvision.transforms.RandomCrop(config.crop_shape)
            else:
                self.maybe_random_crop = self.center_crop
        else:
            self.do_crop = False

        # Set up backbone.
        backbone_model = getattr(torchvision.models, config.vision_backbone)(
            weights=config.pretrained_backbone_weights
        )
        # Note: This assumes that the layer4 feature map is children()[-3]
        # TODO(alexander-soare): Use a safer alternative.
        self.backbone = nn.Sequential(*(list(backbone_model.children())[:-2]))
        if config.use_group_norm:
            if config.pretrained_backbone_weights:
                raise ValueError(
                    "You can't replace BatchNorm in a pretrained model without ruining the weights!"
                )
            self.backbone = _replace_submodules(
                root_module=self.backbone,
                predicate=lambda x: isinstance(x, nn.BatchNorm2d),
                func=lambda x: nn.GroupNorm(num_groups=x.num_features // 16, num_channels=x.num_features),
            )

        # Set up pooling and final layers.
        # Use a dry run to get the feature map shape.
        # The dummy input should take the number of image channels from `config.image_features` and it should
        # use the height and width from `config.crop_shape` if it is provided, otherwise it should use the
        # height and width from `config.image_features`.

        # Note: we have a check in the config class to make sure all images have the same shape.
        images_shape = next(iter(config.image_features.values())).shape
        dummy_shape_h_w = config.crop_shape if config.crop_shape is not None else images_shape[1:]
        dummy_shape = (1, images_shape[0], *dummy_shape_h_w)
        feature_map_shape = get_output_shape(self.backbone, dummy_shape)[1:]

        self.pool = SpatialSoftmax(feature_map_shape, num_kp=config.spatial_softmax_num_keypoints)
        self.feature_dim = config.spatial_softmax_num_keypoints * 2
        self.out = nn.Linear(config.spatial_softmax_num_keypoints * 2, self.feature_dim)
        self.relu = nn.ReLU()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: (B, C, H, W) image tensor with pixel values in [0, 1].
        Returns:
            (B, D) image feature.
        """
        # Preprocess: maybe crop (if it was set up in the __init__).
        if self.do_crop:
            if self.training:  # noqa: SIM108
                x = self.maybe_random_crop(x)
            else:
                # Always use center crop for eval.
                x = self.center_crop(x)
        # Extract backbone feature.
        x = torch.flatten(self.pool(self.backbone(x)), start_dim=1)
        # Final linear layer with non-linearity.
        x = self.relu(self.out(x))
        return x


def _replace_submodules(
    root_module: nn.Module, predicate: Callable[[nn.Module], bool], func: Callable[[nn.Module], nn.Module]
) -> nn.Module:
    """
    Args:
        root_module: The module for which the submodules need to be replaced
        predicate: Takes a module as an argument and must return True if the that module is to be replaced.
        func: Takes a module as an argument and returns a new module to replace it with.
    Returns:
        The root module with its submodules replaced.
    """
    if predicate(root_module):
        return func(root_module)

    replace_list = [k.split(".") for k, m in root_module.named_modules(remove_duplicate=True) if predicate(m)]
    for *parents, k in replace_list:
        parent_module = root_module
        if len(parents) > 0:
            parent_module = root_module.get_submodule(".".join(parents))
        if isinstance(parent_module, nn.Sequential):
            src_module = parent_module[int(k)]
        else:
            src_module = getattr(parent_module, k)
        tgt_module = func(src_module)
        if isinstance(parent_module, nn.Sequential):
            parent_module[int(k)] = tgt_module
        else:
            setattr(parent_module, k, tgt_module)
    # verify that all BN are replaced
    assert not any(predicate(m) for _, m in root_module.named_modules(remove_duplicate=True))
    return root_module
